### PR TITLE
feat: upgrade to ionic 7

### PR DESCRIPTION
**Pull request by oumarbarry**
The ion-slides and ion-slide components have been removed in favor of using Swiper.js directly. The nuxt-swiper module can be used in place.

The ion-virtual-scroll component has been removed in favor of using solutions provided by each JavaScript Framework. 
vue-virtual-scroller can be used in place per example.

The packages @ionic/vue and @ionic/vue-router have been updated to no longer include a CommonJS entry point, and now only provide an ES Module entry point. This change has been made to improve compatibility with Vite.
Regarding the optimization of these packages, the question is whether it's still necessary to include '@ionic/vue' in the 'vite.optimizeDeps.include' array.

### CODE REVIEW

**Comment by oumarbarry** [comment]
@danielroe
question by the way: is it still necessary to include '@ionic/vue' in the 'vite.optimizeDeps.include' array ?
as @ionic/vue have been updated to no longer include a CommonJS entry point, and now only provide an ES Module entry point

**Comment by danielroe** [comment]
You're right, I think we can omit it now.

**Review by danielroe — APPROVED** [review]

**Comment by Tragio** [comment]
@danielroe did you forget to release a version of the package or are you waiting for something? 😋

**Comment by danielroe** [comment]
don't lose heart - coming soon!

**Pull request merged**
