### PR TITLE
feat: replace `useHead` with ionic-compatible head implementation

### PR DESCRIPTION
**Pull request by CHIBX**
I created an utility function, **useIonHead**, that works almost the same as **useHead** from **unhead**, but just with a hack around. 
The function provides a way to dispose and patch the created head object just like **useHead**. 
During the process, I realized that tabbed view was a big problem when trying to create this util, and the randomness of the Ionic Hooks. The main issue was leaving from a tabbed view to a non-tabbed view and trying to mantain or destroy state. 
**Guess What:** You can nest **useIonHead** calls within children components and still retain the same structure after the page it was created on, is brought into view, and it's also fast as well.

resolves https://github.com/nuxt-modules/ionic/issues/6

### CODE REVIEW

**Comment by danielroe** [comment]
This is fantastic! Do you think we should overwrite `useHead` instead of creating an additional composable?

**Comment by CHIBX** [comment]
> This is fantastic! Do you think we should overwrite `useHead` instead of creating an additional composable?

Sure, I guess changing the name to useHead would be better for ease when working with ongoing projects

**Review by danielroe — COMMENTED** [review]
I think the next step would be to write a browser test that asserts the correct title after client navigation, following the pattern here:

https://github.com/danielroe/nuxt-ionic/blob/a45c95693f1fdb8de0be43d7a664db72989effd2/test/e2e/ssr.spec.ts#L27-L36

Is that something you would be happy & able to do?

**Comment by CHIBX** [comment]
> I think the next step would be to write a browser test that asserts the correct title after client navigation, following the pattern here:
> 
> https://github.com/danielroe/nuxt-ionic/blob/a45c95693f1fdb8de0be43d7a664db72989effd2/test/e2e/ssr.spec.ts#L27-L36
> 
> Is that something you would be happy & able to do?

@danielroe I will be able to do this

**Comment by CHIBX** [comment]
@danielroe  Already created a new test in the **`e2e/ion-head.spec.ts`** file, and also changed **`useIonHead`** to **`useHead`** with a higher priority.

Made a few more changes to the tests due to timeout and memory consumption from previously ongoing tests, **`ssr.spec.ts`**, by closing the open page, shaving off a huge amount of allocated memory. 

I added delays after each toggle of the button in the test to represent the delay that useHead takes to rectify changes to the document's head tag, but this brought about a reason to increase the timeout for the test.

I hope the test satisfies the required condition

**Review by danielroe — APPROVED** [review]
Thank you so much for this ❤️

**Comment by danielroe** [comment]
cc: @harlan-zw - you may have a better idea or improvements to suggest

**Review by CHIBX — COMMENTED** [review]
@danielroe Thanks for correcting the test. This obviously looks better.

**Comment by harlan-zw** [comment]
I'm not entirely sure I understand the issue, the Ionic lifecycle hooks don't align with the Vue lifecycle hooks?

If you have any capacity to make an issue on the Unhead repo with some technical background I'd be happy to explore some alternative ways of solving it that don't rely on new composables.

This solution seems quite good though, nice job!

**Comment by atakansn** [comment]
hello, I can not useHead, what should I do?

**Comment by atakansn** [comment]
@chibx @unhead/vue version 2.0.0-rc.8 I use nuxt 3 and @nuxtjs/ionic side

**Comment by chibx** [comment]
> @chibx @unhead/vue version 2.0.0-rc.8 I use nuxt 3 and @nuxtjs/ionic side

I suppose this is why
The next question would be if you are importing directly from useHead or from #imports, and if not from #imports, please try that
If the issues persist, try setting the `head.legacy` key in your Nuxt config to true

**Comment by atakansn** [comment]
I'm doing auto import I'll try with #imports

**Comment by atakansn** [comment]
@chibx When I `import { useHead } from '@unhead/vue'` or `import { useHead } from '#app'`, useHead works.

**Comment by atakansn** [comment]
```
useHead({
  title: 'Title',
  htmlAttrs: {
    class: 'h-full bg-gray-100'
  },  
  meta: [
    { name: 'description', content: 'My amazing site.' }
  ],
  bodyAttrs: {
    class: 'test'
  },
  script: [ { innerHTML: 'console.log(\'Hello world\')' } ]
})
```

in the example it adds all properties

**Pull request merged**
